export const DELETE_IMAGE = 'DELETE_IMAGE';

export const SET_IMAGE = 'SET_IMAGE';

export const START_LOADING_IMAGE = 'START_LOADING_IMAGE';

export const FINISH_LOADING_IMAGE = 'FINISH_LOADING_IMAGE';

export const START_IMAGE_PROCESSING = 'START_IMAGE_PROCESSING';

export const FINISH_IMAGE_PROCESSING = 'FINISH_IMAGE_PROCESSING';
